site_name: MPSdocs
site_url: https://www.example.com
nav:
    - Home: index.md
    - About: about.md

theme:
   name: readthedocs

plugins:
  - search
  - build_plantuml:
      render: "server" # or "local" for local rendering
      bin_path: "/usr/local/bin/plantuml" # ignored when render: server
      server: "http://www.plantuml.com/plantuml" # offical plantuml server
      output_format: "svg" # or "png"
      diagram_root: "docs/diagrams" # should reside under docs_dir
      output_folder: "out"
      input_folder: "src"
      input_extensions: "" # comma separated list of extensions to parse, by default every file is parsed

markdown_extensions:
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml